# Generated by Django 4.2 on 2025-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebody',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/service_images/'),
        ),
    ]
